name: Publish Release

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - .github/workflows/*
      - .devcontainer/*

jobs:
  publish:
    runs-on: windows-latest
    env:
      python_ver: 3.11
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.python-ver }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python-ver }}
      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'plugin.json'
          prop_path: 'Version'
      - run: echo ${{steps.version.outputs.prop}} 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt -t ./lib
          Remove-Item ./lib/PIL -recurse
          Remove-Item ./lib/Pillow-* -recurse
          pip install --platform win_amd64 --only-binary=:all: Pillow -t ./lib
          $exclude = @("*.git*", ".devcontainer")
          $files = Get-ChildItem -Path . -Exclude $exclude
          Compress-Archive -Path $files -DestinationPath Flow.Launcher.Plugin.MemeFlow.zip
      - name: Publish
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          files: 'Flow.Launcher.Plugin.MemeFlow.zip'
          tag_name: "v${{steps.version.outputs.prop}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}